from app.models.user import User
from app.models.student import Student
from app.models.additional_student_info import AdditionalStudentInfo
from app.models.student_registration import StudentRegistration
from app.models.teacher import Teacher
from app.models.course import Course
from app.models.enrollment import Enrollment
from app.models.test import Test
from app.models.test_result import TestResult
from app.models.interview_notes import InterviewNotes
from app.models.report_card import ReportCard
